version: '2.1'
services:
  db:
    image: postgres:9
    volumes:
      - "/srv/getin-template:/var/lib/postgresql/data"
    healthcheck:
      test: pg_isready -h localhost -p 5432 -q -U postgres -d postgres
      interval: 5s
      timeout: 5s
      retries: 5

  db_setup:
    build: ./server
    command: python setup_db.py
    volumes:
      - "./server:/srv/app"
    depends_on:
      db:
        condition: service_healthy

  server:
    build: ./server
    command: gunicorn --access-logfile - -w 3 -b 0.0.0.0:80 app:app
    volumes:
      - "./server:/srv/app"
    depends_on:
      - db_setup

  nginx:
    image: nginx:stable
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./client/dist:/usr/share/nginx/html"
    ports:
      - "80:80"
    depends_on:
      - server
